#!/usr/bin/env perl

# adapted from Steve Ivy's Wiring Notational Velocity to a Github Wiki
# http://monkinetic.com/2011/02/08/wiring-notational-velocity-to-a-github-wiki.html
 
my $USER='fkh';
my $status= `cd /Users/$USER/Library/Application\\ Support/Notational\\ Data/; /usr/local/git/bin/git status`;

if ($status =~ /modified|untracked\ files\ present|deleted/) {
    my $out = `cd /Users/$USER/Library/Application\\ Support/Notational\\ Data/; /usr/local/git/bin/git add .; /usr/local/git/bin/git commit -a -m "task update";`;
				} else {
				    print "NV Wiki Update: No update needed.\n"
						}
